wipe = true

no-tests = true

output = "gen/sqlboiler" 
pkgname = "sqlboiler"

add-global-variants = true
add-enum-types = true

[sqlite3]
dbname = "/home/abc-valera/dev/personal/netsly-golang/internal/infrastructure/persistence/implementation/boilerSqlite/sqlite.db"