#!/usr/bin/bash

echo "Running pre-commit script...⏳"

# TODO: maybe add linters here

# Run the tests
if ! task test:unit; then
    echo "Unit tests failed 🚫"
    exit 1
fi

if ! task test:integration; then
    echo "Integration tests failed🚫"
    exit 1
fi

# Run go mod tidy
go mod tidy
git add go.mod go.sum

echo "Pre-commit checks passed!✅"
exit 0
