openapi: 3.0.0
info:
  version: 0.1.0
  title: Netsly API
  termsOfService: "https://github.com/abc-valera/netsly-golang"
  contact:
    email: zoocity14@gmail.com
    url: "https://github.com/abc-valera/netsly-golang"
  description: API for Netsly social network
externalDocs:
  description: Learn more about the project.
  url: "https://github.com/abc-valera/netsly-golang"
tags:
  - name: sign
    description: Everything about managing user sessions
  - name: me
    description: Everything about managing current user profile
  - name: rooms
    description: Everything about managing rooms
  - name: users
    description: Everything about searching users
  - name: jokes
    description: Everything about searching jokes
  - name: comments
    description: Everything about searching comments
  - name: likes
    description: Everything about counting likes
paths:
  /sign/up:
    $ref: paths/sign/up.yaml
  /sign/in:
    $ref: paths/sign/in.yaml
  /sign/refresh:
    $ref: paths/sign/refresh.yaml
  /me:
    $ref: paths/me/_.yaml
  /me/jokes:
    $ref: paths/me/jokes.yaml
  /me/comments:
    $ref: paths/me/comments.yaml
  /me/likes:
    $ref: paths/me/likes.yaml
  /me/rooms:
    $ref: paths/me/rooms/_.yaml
  /me/rooms/join:
    $ref: paths/me/rooms/join.yaml
  /rooms/{room_id}/messages:
    $ref: paths/rooms/{room_id}_messages.yaml
  /comments/{joke_id}:
    $ref: paths/comments/{joke_id}.yaml
  /likes/{joke_id}:
    $ref: paths/likes/{joke_id}.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
