# https://taskfile.dev

version: "3"

env:
  GOOSE_MIGRATION_DIR: "internal/persistence/sqlboilerImpl/migration"
  GOOSE_DRIVER: "postgres"
  GOOSE_DBSTRING: "postgres://netsly:netsly@localhost:5432/netsly?sslmode=disable"

vars:
  ENV_FILE_PATH: "env/dev.env"

tasks:
  entrypoint:jsonApi:
    dotenv: ["{{ .ENV_FILE_PATH }}"]
    cmds:
      - go build -o build/netsly cmd/main.go
      - ./build/netsly -entrypoint jsonApi

  entrypoint:webApp:
    dotenv: ["{{ .ENV_FILE_PATH }}"]
    cmds:
      - go build -o build/netsly cmd/main.go
      - ./build/netsly -entrypoint webApp

  entrypoint:grpcApi:
    dotenv: ["{{ .ENV_FILE_PATH }}"]
    cmds:
      - go build -o build/netsly cmd/main.go
      - ./build/netsly -entrypoint grpcApi

  entrypoint:seed:
    dotenv: ["{{ .ENV_FILE_PATH }}"]
    cmds:
      - go build -o build/netsly cmd/main.go
      - ./build/netsly -entrypoint seed

  test:unit:
    cmds:
      - go test ./internal/application/ -count=1

  test:integration:
    cmds:
      - task: test:integration:persistence
      - task: test:integration:service

  test:integration:persistence:
    cmds:
      - go test ./test/persistence -count=1

  test:integration:service:
    cmds:
      - go test ./test/service -count=1

  generate:domain:mocks:
    cmds:
      - mockery --config internal/domain/mock/mockery.yaml

  generate:jsonApi:main:
    desc: Generate docs and code for the HTTP presentation from the OpenAPI spec directory
    cmds:
      - task: generate:jsonApi:rest:single_openapi_config_file
      - task: generate:jsonApi:rest:docs
      - task: generate:jsonApi:rest:code

  generate:jsonApi:rest:single_openapi_config_file:
    cmds:
      - docker run --rm -v ${PWD}:/spec:Z
        redocly/cli bundle
        -o /spec/gen/openapi/openapi.yaml
        /spec/internal/presentation/jsonApi/rest/schema/openapi.yaml

  generate:jsonApi:rest:docs:
    cmds:
      - docker run --rm -v ${PWD}:/spec:Z
        redocly/cli build-docs
        -o /spec/internal/presentation/jsonApi/static/docs/rest.html
        /spec/internal/presentation/jsonApi/rest/schema/openapi.yaml

  generate:jsonApi:rest:code:
    cmds:
      - go generate gen/ogen/generate.go

  generate:webApp:tailwindcss:
    cmds:
      - npx tailwindcss
        -c internal/presentation/webApp/tailwind.config.js
        -i internal/presentation/webApp/static/style/input.css
        -o internal/presentation/webApp/static/style/style.css

  generate:grpcApi:code:
    cmds:
      - protoc internal/presentation/grpcApi/proto/*.proto
        --go_out=gen/pb
        --go_opt=paths=source_relative
        --go-grpc_out=gen/pb
        --go-grpc_opt=paths=source_relative
        --proto_path=internal/presentation/grpcApi/proto

  generate:persistence:migration:
    cmds:
      - goose -s create main sql

  generate:persistence:code:
    cmds:
      - sqlboiler psql -c internal/persistence/sqlboilerImpl/sqlboiler.toml

  infrastructure:up:
    cmds:
      - task: infrastructure:run_postgres
      - task: infrastructure:run_redis

  infrastructure:down:
    cmds:
      - docker rm -f netsly-postgres
      - docker rm -f netsly-redis

  infrastructure:start:
    cmds:
      - docker start netsly-postgres
      - docker start netsly-redis

  infrastructure:stop:
    cmds:
      - docker stop netsly-postgres
      - docker stop netsly-redis

  infrastructure:migrate:
    cmds:
      - goose up

  infrastructure:run_postgres:
    cmds:
      - docker run
        --name netsly-postgres
        --network netsly-network
        -p 5432:5432
        -e POSTGRES_USER=netsly
        -e POSTGRES_PASSWORD=netsly
        -e POSTGRES_DB=netsly
        -d postgres:15-alpine

  infrastructure:run_redis:
    cmds:
      - docker run
        --name netsly-redis
        --network netsly-network
        -p 6379:6379
        -d redis/redis-stack:latest

  image:jsonApi:build:
    cmds:
      - docker build -t netsly/jsonApi:latest -f docker/Dockerfile.jsonApi .

  image:jsonApi:up:
    cmds:
      - docker run
        --name netsly_json-api
        --network netsly-network
        -p 3010:3010
        -e POSTGRES_URL=postgres://netsly:netsly@netsly-postgres:5432/netsly?sslmode=disable
        -e REDIS_PORT=netsly-redis:6379
        -e REDIS_USER=netsly-redis
        -e REDIS_PASS=
        --env-file env/deploy.env
        localhost/netsly/jsonApi:latest

  image:jsonApi:down:
    cmds:
      - docker rm netsly_json-api

  compose:up:
    cmds:
      - docker-compose -f docker/docker-compose.dev.yml --env-file env/deploy.env up -d

  compose:down:
    cmds:
      - docker-compose -f docker/docker-compose.dev.yml down

  other:run_evans:
    cmds:
      - evans -p 3030 -r repl
