# https://taskfile.dev

version: "3"

tasks:
  generate:json-rest-api:main:
    desc: Generate docs and code for the HTTP port from the OpenAPI spec directory
    cmds:
      - task: generate:json-rest-api:single_openapi_config_file
      - task: generate:json-rest-api:docs
      - task: generate:json-rest-api:code

  generate:json-rest-api:single_openapi_config_file:
    cmds:
      - podman run --rm -v ${PWD}:/spec:Z
        docker.io/redocly/cli bundle
        -o /spec/gen/openapi/openapi.yaml
        /spec/internal/port/json-rest-api/schema/openapi.yaml

  generate:json-rest-api:docs:
    cmds:
      - podman run --rm -v ${PWD}:/spec:Z
        docker.io/redocly/cli build-docs
        -o /spec/internal/port/json-rest-api/docs/index.html
        /spec/internal/port/json-rest-api/schema/openapi.yaml

  generate:json-rest-api:code:
    cmds:
      - go generate gen/ogen/generate.go

  generate:web-app:tailwindcss:
    cmds:
      - npx tailwindcss
        -c internal/port/web-app/tailwind.config.js
        -i internal/port/web-app/static/style/input.css
        -o internal/port/web-app/static/style/style.css

  generate:grpc-api:code:
    cmds:
      - rm -f gen/pb/*.pb.go
        protoc internal/port/grpc-api/proto/*.proto
        --go_out=gen/pb
        --go_opt=paths=source_relative
        --go-grpc_out=gen/pb
        --go-grpc_opt=paths=source_relative
        --proto_path=internal/port/grpc-api/proto

  generate:persistance:code:
    cmds:
      - go generate gen/ent/generate.go

  infrastructure:up:
    cmds:
      - podman rm -f flugo-db
      - podman rm -f flugo-redis
      - task: infrastructure:run_postgres
      - task: infrastructure:run_redis

  infrastructure:run_postgres:
    cmds:
      - podman run
        --name flugo-db
        -p 5432:5432
        -e POSTGRES_USER=flugo
        -e POSTGRES_PASSWORD=flugo
        -e POSTGRES_DB=flugo
        -d docker.io/library/postgres:15-alpine

  infrastructure:run_redis:
    cmds:
      - podman run
        --name flugo-redis
        -p 6379:6379
        -d docker.io/redis/redis-stack:latest

  entrypoint:json-rest-api:
    dotenv: ["env/.dev.env"]
    cmds:
      - go build -o build/json-rest-api cmd/json-rest-api/main.go
      - ./build/json-rest-api

  entrypoint:web-app:
    dotenv: ["env/.dev.env"]
    cmds:
      - go build -o build/web-app cmd/web-app/main.go
      - ./build/web-app

  entrypoint:grpc-api:
    dotenv: ["env/.dev.env"]
    cmds:
      - go build -o build/grpc-api cmd/grpc-api/main.go
      - ./build/grpc-api

  other:run_evans:
    cmds:
      - evans -p 3030 -r repl
