// Code generated by mockery. DO NOT EDIT.

package mockQuery

import (
	context "context"

	model "github.com/abc-valera/netsly-api-golang/pkg/domain/persistence/model"
	mock "github.com/stretchr/testify/mock"

	selector "github.com/abc-valera/netsly-api-golang/pkg/domain/persistence/query/selector"
)

// Comment is an autogenerated mock type for the IComment type
type Comment struct {
	mock.Mock
}

type Comment_Expecter struct {
	mock *mock.Mock
}

func (_m *Comment) EXPECT() *Comment_Expecter {
	return &Comment_Expecter{mock: &_m.Mock}
}

// GetAllByJokeID provides a mock function with given fields: ctx, jokeID, params
func (_m *Comment) GetAllByJokeID(ctx context.Context, jokeID string, params selector.Selector) (model.Comments, error) {
	ret := _m.Called(ctx, jokeID, params)

	if len(ret) == 0 {
		panic("no return value specified for GetAllByJokeID")
	}

	var r0 model.Comments
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, selector.Selector) (model.Comments, error)); ok {
		return rf(ctx, jokeID, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, selector.Selector) model.Comments); ok {
		r0 = rf(ctx, jokeID, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(model.Comments)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, selector.Selector) error); ok {
		r1 = rf(ctx, jokeID, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Comment_GetAllByJokeID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllByJokeID'
type Comment_GetAllByJokeID_Call struct {
	*mock.Call
}

// GetAllByJokeID is a helper method to define mock.On call
//   - ctx context.Context
//   - jokeID string
//   - params selector.Selector
func (_e *Comment_Expecter) GetAllByJokeID(ctx interface{}, jokeID interface{}, params interface{}) *Comment_GetAllByJokeID_Call {
	return &Comment_GetAllByJokeID_Call{Call: _e.mock.On("GetAllByJokeID", ctx, jokeID, params)}
}

func (_c *Comment_GetAllByJokeID_Call) Run(run func(ctx context.Context, jokeID string, params selector.Selector)) *Comment_GetAllByJokeID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(selector.Selector))
	})
	return _c
}

func (_c *Comment_GetAllByJokeID_Call) Return(_a0 model.Comments, _a1 error) *Comment_GetAllByJokeID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Comment_GetAllByJokeID_Call) RunAndReturn(run func(context.Context, string, selector.Selector) (model.Comments, error)) *Comment_GetAllByJokeID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *Comment) GetByID(ctx context.Context, id string) (model.Comment, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 model.Comment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (model.Comment, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) model.Comment); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(model.Comment)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Comment_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type Comment_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *Comment_Expecter) GetByID(ctx interface{}, id interface{}) *Comment_GetByID_Call {
	return &Comment_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *Comment_GetByID_Call) Run(run func(ctx context.Context, id string)) *Comment_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Comment_GetByID_Call) Return(_a0 model.Comment, _a1 error) *Comment_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Comment_GetByID_Call) RunAndReturn(run func(context.Context, string) (model.Comment, error)) *Comment_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// NewComment creates a new instance of Comment. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewComment(t interface {
	mock.TestingT
	Cleanup(func())
}) *Comment {
	mock := &Comment{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
