// Code generated by mockery. DO NOT EDIT.

package mockTimeMaker

import (
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// TimeMaker is an autogenerated mock type for the ITimeMaker type
type TimeMaker struct {
	mock.Mock
}

type TimeMaker_Expecter struct {
	mock *mock.Mock
}

func (_m *TimeMaker) EXPECT() *TimeMaker_Expecter {
	return &TimeMaker_Expecter{mock: &_m.Mock}
}

// Now provides a mock function with given fields:
func (_m *TimeMaker) Now() time.Time {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Now")
	}

	var r0 time.Time
	if rf, ok := ret.Get(0).(func() time.Time); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(time.Time)
	}

	return r0
}

// TimeMaker_Now_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Now'
type TimeMaker_Now_Call struct {
	*mock.Call
}

// Now is a helper method to define mock.On call
func (_e *TimeMaker_Expecter) Now() *TimeMaker_Now_Call {
	return &TimeMaker_Now_Call{Call: _e.mock.On("Now")}
}

func (_c *TimeMaker_Now_Call) Run(run func()) *TimeMaker_Now_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *TimeMaker_Now_Call) Return(_a0 time.Time) *TimeMaker_Now_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TimeMaker_Now_Call) RunAndReturn(run func() time.Time) *TimeMaker_Now_Call {
	_c.Call.Return(run)
	return _c
}

// NewTimeMaker creates a new instance of TimeMaker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTimeMaker(t interface {
	mock.TestingT
	Cleanup(func())
}) *TimeMaker {
	mock := &TimeMaker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
