// Code generated by mockery. DO NOT EDIT.

package command

import (
	context "context"

	model "github.com/abc-valera/netsly-api-golang/internal/domain/persistence/model"
	mock "github.com/stretchr/testify/mock"
)

// MockComment is an autogenerated mock type for the IComment type
type MockComment struct {
	mock.Mock
}

type MockComment_Expecter struct {
	mock *mock.Mock
}

func (_m *MockComment) EXPECT() *MockComment_Expecter {
	return &MockComment_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, req
func (_m *MockComment) Create(ctx context.Context, req model.Comment) (model.Comment, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 model.Comment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Comment) (model.Comment, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.Comment) model.Comment); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(model.Comment)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.Comment) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockComment_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockComment_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - req model.Comment
func (_e *MockComment_Expecter) Create(ctx interface{}, req interface{}) *MockComment_Create_Call {
	return &MockComment_Create_Call{Call: _e.mock.On("Create", ctx, req)}
}

func (_c *MockComment_Create_Call) Run(run func(ctx context.Context, req model.Comment)) *MockComment_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.Comment))
	})
	return _c
}

func (_c *MockComment_Create_Call) Return(_a0 model.Comment, _a1 error) *MockComment_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockComment_Create_Call) RunAndReturn(run func(context.Context, model.Comment) (model.Comment, error)) *MockComment_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockComment) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockComment_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockComment_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockComment_Expecter) Delete(ctx interface{}, id interface{}) *MockComment_Delete_Call {
	return &MockComment_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockComment_Delete_Call) Run(run func(ctx context.Context, id string)) *MockComment_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockComment_Delete_Call) Return(_a0 error) *MockComment_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockComment_Delete_Call) RunAndReturn(run func(context.Context, string) error) *MockComment_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, commentID, req
func (_m *MockComment) Update(ctx context.Context, commentID string, req CommentUpdate) (model.Comment, error) {
	ret := _m.Called(ctx, commentID, req)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 model.Comment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, CommentUpdate) (model.Comment, error)); ok {
		return rf(ctx, commentID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, CommentUpdate) model.Comment); ok {
		r0 = rf(ctx, commentID, req)
	} else {
		r0 = ret.Get(0).(model.Comment)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, CommentUpdate) error); ok {
		r1 = rf(ctx, commentID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockComment_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockComment_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - commentID string
//   - req CommentUpdate
func (_e *MockComment_Expecter) Update(ctx interface{}, commentID interface{}, req interface{}) *MockComment_Update_Call {
	return &MockComment_Update_Call{Call: _e.mock.On("Update", ctx, commentID, req)}
}

func (_c *MockComment_Update_Call) Run(run func(ctx context.Context, commentID string, req CommentUpdate)) *MockComment_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(CommentUpdate))
	})
	return _c
}

func (_c *MockComment_Update_Call) Return(_a0 model.Comment, _a1 error) *MockComment_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockComment_Update_Call) RunAndReturn(run func(context.Context, string, CommentUpdate) (model.Comment, error)) *MockComment_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockComment creates a new instance of MockComment. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockComment(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockComment {
	mock := &MockComment{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
