// Code generated by mockery. DO NOT EDIT.

package command

import (
	context "context"

	model "github.com/abc-valera/netsly-api-golang/internal/domain/persistence/model"
	mock "github.com/stretchr/testify/mock"
)

// MockJoke is an autogenerated mock type for the IJoke type
type MockJoke struct {
	mock.Mock
}

type MockJoke_Expecter struct {
	mock *mock.Mock
}

func (_m *MockJoke) EXPECT() *MockJoke_Expecter {
	return &MockJoke_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, req
func (_m *MockJoke) Create(ctx context.Context, req model.Joke) (model.Joke, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 model.Joke
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Joke) (model.Joke, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.Joke) model.Joke); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(model.Joke)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.Joke) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockJoke_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockJoke_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - req model.Joke
func (_e *MockJoke_Expecter) Create(ctx interface{}, req interface{}) *MockJoke_Create_Call {
	return &MockJoke_Create_Call{Call: _e.mock.On("Create", ctx, req)}
}

func (_c *MockJoke_Create_Call) Run(run func(ctx context.Context, req model.Joke)) *MockJoke_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.Joke))
	})
	return _c
}

func (_c *MockJoke_Create_Call) Return(_a0 model.Joke, _a1 error) *MockJoke_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockJoke_Create_Call) RunAndReturn(run func(context.Context, model.Joke) (model.Joke, error)) *MockJoke_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockJoke) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockJoke_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockJoke_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockJoke_Expecter) Delete(ctx interface{}, id interface{}) *MockJoke_Delete_Call {
	return &MockJoke_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockJoke_Delete_Call) Run(run func(ctx context.Context, id string)) *MockJoke_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockJoke_Delete_Call) Return(_a0 error) *MockJoke_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockJoke_Delete_Call) RunAndReturn(run func(context.Context, string) error) *MockJoke_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, id, req
func (_m *MockJoke) Update(ctx context.Context, id string, req JokeUpdate) (model.Joke, error) {
	ret := _m.Called(ctx, id, req)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 model.Joke
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, JokeUpdate) (model.Joke, error)); ok {
		return rf(ctx, id, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, JokeUpdate) model.Joke); ok {
		r0 = rf(ctx, id, req)
	} else {
		r0 = ret.Get(0).(model.Joke)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, JokeUpdate) error); ok {
		r1 = rf(ctx, id, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockJoke_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockJoke_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - req JokeUpdate
func (_e *MockJoke_Expecter) Update(ctx interface{}, id interface{}, req interface{}) *MockJoke_Update_Call {
	return &MockJoke_Update_Call{Call: _e.mock.On("Update", ctx, id, req)}
}

func (_c *MockJoke_Update_Call) Run(run func(ctx context.Context, id string, req JokeUpdate)) *MockJoke_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(JokeUpdate))
	})
	return _c
}

func (_c *MockJoke_Update_Call) Return(_a0 model.Joke, _a1 error) *MockJoke_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockJoke_Update_Call) RunAndReturn(run func(context.Context, string, JokeUpdate) (model.Joke, error)) *MockJoke_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockJoke creates a new instance of MockJoke. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockJoke(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockJoke {
	mock := &MockJoke{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
