// Code generated by mockery. DO NOT EDIT.

package command

import (
	context "context"

	model "github.com/abc-valera/netsly-api-golang/internal/domain/persistence/model"
	mock "github.com/stretchr/testify/mock"
)

// MockRoomMessage is an autogenerated mock type for the IRoomMessage type
type MockRoomMessage struct {
	mock.Mock
}

type MockRoomMessage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRoomMessage) EXPECT() *MockRoomMessage_Expecter {
	return &MockRoomMessage_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, req
func (_m *MockRoomMessage) Create(ctx context.Context, req model.RoomMessage) (model.RoomMessage, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 model.RoomMessage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.RoomMessage) (model.RoomMessage, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.RoomMessage) model.RoomMessage); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(model.RoomMessage)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.RoomMessage) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoomMessage_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRoomMessage_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - req model.RoomMessage
func (_e *MockRoomMessage_Expecter) Create(ctx interface{}, req interface{}) *MockRoomMessage_Create_Call {
	return &MockRoomMessage_Create_Call{Call: _e.mock.On("Create", ctx, req)}
}

func (_c *MockRoomMessage_Create_Call) Run(run func(ctx context.Context, req model.RoomMessage)) *MockRoomMessage_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.RoomMessage))
	})
	return _c
}

func (_c *MockRoomMessage_Create_Call) Return(_a0 model.RoomMessage, _a1 error) *MockRoomMessage_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoomMessage_Create_Call) RunAndReturn(run func(context.Context, model.RoomMessage) (model.RoomMessage, error)) *MockRoomMessage_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockRoomMessage) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRoomMessage_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockRoomMessage_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockRoomMessage_Expecter) Delete(ctx interface{}, id interface{}) *MockRoomMessage_Delete_Call {
	return &MockRoomMessage_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockRoomMessage_Delete_Call) Run(run func(ctx context.Context, id string)) *MockRoomMessage_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRoomMessage_Delete_Call) Return(_a0 error) *MockRoomMessage_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRoomMessage_Delete_Call) RunAndReturn(run func(context.Context, string) error) *MockRoomMessage_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, id, req
func (_m *MockRoomMessage) Update(ctx context.Context, id string, req RoomMessageUpdate) (model.RoomMessage, error) {
	ret := _m.Called(ctx, id, req)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 model.RoomMessage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, RoomMessageUpdate) (model.RoomMessage, error)); ok {
		return rf(ctx, id, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, RoomMessageUpdate) model.RoomMessage); ok {
		r0 = rf(ctx, id, req)
	} else {
		r0 = ret.Get(0).(model.RoomMessage)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, RoomMessageUpdate) error); ok {
		r1 = rf(ctx, id, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoomMessage_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockRoomMessage_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - req RoomMessageUpdate
func (_e *MockRoomMessage_Expecter) Update(ctx interface{}, id interface{}, req interface{}) *MockRoomMessage_Update_Call {
	return &MockRoomMessage_Update_Call{Call: _e.mock.On("Update", ctx, id, req)}
}

func (_c *MockRoomMessage_Update_Call) Run(run func(ctx context.Context, id string, req RoomMessageUpdate)) *MockRoomMessage_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(RoomMessageUpdate))
	})
	return _c
}

func (_c *MockRoomMessage_Update_Call) Return(_a0 model.RoomMessage, _a1 error) *MockRoomMessage_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoomMessage_Update_Call) RunAndReturn(run func(context.Context, string, RoomMessageUpdate) (model.RoomMessage, error)) *MockRoomMessage_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRoomMessage creates a new instance of MockRoomMessage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRoomMessage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRoomMessage {
	mock := &MockRoomMessage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
