// Code generated by mockery. DO NOT EDIT.

package command

import (
	context "context"

	model "github.com/abc-valera/netsly-api-golang/internal/domain/persistence/model"
	mock "github.com/stretchr/testify/mock"
)

// MockRoom is an autogenerated mock type for the IRoom type
type MockRoom struct {
	mock.Mock
}

type MockRoom_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRoom) EXPECT() *MockRoom_Expecter {
	return &MockRoom_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, req
func (_m *MockRoom) Create(ctx context.Context, req model.Room) (model.Room, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 model.Room
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Room) (model.Room, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.Room) model.Room); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(model.Room)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.Room) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoom_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRoom_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - req model.Room
func (_e *MockRoom_Expecter) Create(ctx interface{}, req interface{}) *MockRoom_Create_Call {
	return &MockRoom_Create_Call{Call: _e.mock.On("Create", ctx, req)}
}

func (_c *MockRoom_Create_Call) Run(run func(ctx context.Context, req model.Room)) *MockRoom_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.Room))
	})
	return _c
}

func (_c *MockRoom_Create_Call) Return(_a0 model.Room, _a1 error) *MockRoom_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoom_Create_Call) RunAndReturn(run func(context.Context, model.Room) (model.Room, error)) *MockRoom_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockRoom) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRoom_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockRoom_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockRoom_Expecter) Delete(ctx interface{}, id interface{}) *MockRoom_Delete_Call {
	return &MockRoom_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockRoom_Delete_Call) Run(run func(ctx context.Context, id string)) *MockRoom_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRoom_Delete_Call) Return(_a0 error) *MockRoom_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRoom_Delete_Call) RunAndReturn(run func(context.Context, string) error) *MockRoom_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, id, req
func (_m *MockRoom) Update(ctx context.Context, id string, req RoomUpdate) (model.Room, error) {
	ret := _m.Called(ctx, id, req)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 model.Room
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, RoomUpdate) (model.Room, error)); ok {
		return rf(ctx, id, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, RoomUpdate) model.Room); ok {
		r0 = rf(ctx, id, req)
	} else {
		r0 = ret.Get(0).(model.Room)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, RoomUpdate) error); ok {
		r1 = rf(ctx, id, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoom_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockRoom_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - req RoomUpdate
func (_e *MockRoom_Expecter) Update(ctx interface{}, id interface{}, req interface{}) *MockRoom_Update_Call {
	return &MockRoom_Update_Call{Call: _e.mock.On("Update", ctx, id, req)}
}

func (_c *MockRoom_Update_Call) Run(run func(ctx context.Context, id string, req RoomUpdate)) *MockRoom_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(RoomUpdate))
	})
	return _c
}

func (_c *MockRoom_Update_Call) Return(_a0 model.Room, _a1 error) *MockRoom_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoom_Update_Call) RunAndReturn(run func(context.Context, string, RoomUpdate) (model.Room, error)) *MockRoom_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRoom creates a new instance of MockRoom. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRoom(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRoom {
	mock := &MockRoom{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
