openapi: 3.0.0
info:
  version: 0.1.0
  title: Flugo API
  termsOfService: https://github.com/abc-valera/flugo-api-golang
  contact:
    email: zoocity14@gmail.com
    url: https://github.com/abc-valera/flugo-api-golang
  description: API for Flugo social network
servers:
  - url: http://localhost:3000
tags:
  - name: sign
    description: Everything about managing user sessions
  - name: me
    description: Everything about managing current user profile
  - name: users
    description: Everything about finding users
  - name: jokes
    description: Everything about finding jokes
  - name: comments
    description: Everything about finding comments
externalDocs:
  description: Learn more about the project.
  url: https://github.com/abc-valera/flugo-api-golang
paths:
  /sign_up:
    post:
      tags:
        - sign
      summary: Performs user registration
      requestBody:
        description: Data to add new user to the social network
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: user1
                email:
                  type: string
                  example: user1@gmail.com
                password:
                  type: string
                  example: 123456789
              required:
                - username
                - email
                - password
      responses:
        '201':
          description: Successful operation
        default:
          $ref: '#/components/responses/code_error'
  /sign_in:
    post:
      tags:
        - sign
      summary: Performs user authentication
      requestBody:
        description: Data to perform sign in to the social network
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: user1@gmail.com
                password:
                  type: string
                  example: 123456789
              required:
                - email
                - password
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  userResponse:
                    $ref: '#/components/schemas/user'
                  accessToken:
                    type: string
                    example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9
                  refreshToken:
                    type: string
                    example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9
                required:
                  - userResponse
                  - accessToken
                  - refreshToken
        default:
          $ref: '#/components/responses/code_error'
  /sign_refresh:
    post:
      tags:
        - sign
      summary: Exchanges a refresh token for an access token
      requestBody:
        description: Refresh token
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                refreshToken:
                  type: string
                  example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9
              required:
                - refreshToken
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
                    example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9
                required:
                  - accessToken
        default:
          $ref: '#/components/responses/code_error'
  /me:
    get:
      tags:
        - me
      summary: Returns current user profile
      security:
        - bearerAuth: []
      responses:
        '200':
          $ref: '#/components/responses/user'
        default:
          $ref: '#/components/responses/code_error'
    put:
      tags:
        - me
      summary: Updates current user profile
      security:
        - bearerAuth: []
      requestBody:
        description: Data to update the current user profile
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: string
                  example: 48690945-c3f9-45b4-9045-c6bcfb898f20
                username:
                  type: string
                  example: johndoe
                fullname:
                  type: string
                  example: John Doe
                status:
                  type: string
                  example: active
              required:
                - user_id
      responses:
        '204':
          description: Successful operation
        default:
          $ref: '#/components/responses/code_error'
    delete:
      tags:
        - me
      summary: Deletes current user profile
      security:
        - bearerAuth: []
      requestBody:
        description: Data to delete the current user profile
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: string
                  example: 48690945-c3f9-45b4-9045-c6bcfb898f20
              required:
                - user_id
      responses:
        '204':
          description: Successful operation
        default:
          $ref: '#/components/responses/code_error'
  /me/jokes:
    get:
      tags:
        - me
      summary: Returns jokes of the current user
      security:
        - bearerAuth: []
      responses:
        '200':
          $ref: '#/components/responses/jokes'
        default:
          $ref: '#/components/responses/code_error'
    post:
      tags:
        - me
      summary: Creates a new joke for current user
      security:
        - bearerAuth: []
      requestBody:
        description: Data to create a new joke for current user
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: string
                  example: '1'
                title:
                  type: string
                  example: Joke title
                text:
                  type: string
                  example: Joke text
                explanation:
                  type: string
                  example: Joke explanation
              required:
                - user_id
                - title
                - text
      responses:
        '201':
          description: Successful operation
        default:
          $ref: '#/components/responses/code_error'
    put:
      tags:
        - me
      summary: Updates joke for current user
      security:
        - bearerAuth: []
      requestBody:
        description: Data to update the joke for current user
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                joke_id:
                  type: string
                  example: 48690945-c3f9-45b4-9045-c6bcfb898f20
                title:
                  type: string
                  example: Joke title
                text:
                  type: string
                  example: Joke text
                explanation:
                  type: string
                  example: Joke explanation
      responses:
        '201':
          description: Successful operation
        default:
          $ref: '#/components/responses/code_error'
    delete:
      tags:
        - me
      summary: Deletes joke for current user
      security:
        - bearerAuth: []
      requestBody:
        description: Data to delete the joke for current user
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                joke_id:
                  type: string
                  example: 48690945-c3f9-45b4-9045-c6bcfb898f20
              required:
                - joke_id
      responses:
        '204':
          description: Successful operation
        default:
          $ref: '#/components/responses/code_error'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    code_error:
      type: object
      title: CodeError
      properties:
        code:
          type: string
          enum:
            - unauthenticated
            - invalid_argument
            - not_found
            - already_exists
            - permission_denied
            - internal
        message:
          type: string
      required:
        - code
        - message
    user:
      type: object
      properties:
        id:
          type: string
          example: 48690945-c3f9-45b4-9045-c6bcfb898f20
        username:
          type: string
          example: user1
        email:
          type: string
          example: user1@gmail.com
        fullname:
          type: string
          example: User 1
        status:
          type: string
          example: Just coding
        created_at:
          type: string
          format: date-time
          example: '2021-08-01T00:00:00Z'
      required:
        - id
        - username
        - email
        - created_at
    joke:
      type: object
      properties:
        id:
          type: string
        userID:
          type: string
        title:
          type: string
          example: Joke 1
        text:
          type: string
          example: Text of joke 1
        explanation:
          type: string
          example: Explanation of joke 1
        createdAt:
          type: string
          format: date-time
          example: '2021-08-01T00:00:00Z'
      required:
        - id
        - userID
        - title
        - text
        - createdAt
  responses:
    code_error:
      description: General Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/code_error'
    user:
      description: User profile
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/user'
    jokes:
      description: Array of jokes
      content:
        application/json:
          schema:
            type: object
            properties:
              jokes:
                type: array
                items:
                  $ref: '#/components/schemas/joke'
            required:
              - jokes
