// Code generated by mockery. DO NOT EDIT.

package mockEntity

import (
	context "context"

	entity "github.com/abc-valera/netsly-api-golang/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"

	model "github.com/abc-valera/netsly-api-golang/internal/domain/persistence/model"
)

// User is an autogenerated mock type for the IUser type
type User struct {
	mock.Mock
}

type User_Expecter struct {
	mock *mock.Mock
}

func (_m *User) EXPECT() *User_Expecter {
	return &User_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, req
func (_m *User) Create(ctx context.Context, req entity.UserCreateRequest) (model.User, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 model.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.UserCreateRequest) (model.User, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.UserCreateRequest) model.User); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(model.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.UserCreateRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// User_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type User_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - req entity.UserCreateRequest
func (_e *User_Expecter) Create(ctx interface{}, req interface{}) *User_Create_Call {
	return &User_Create_Call{Call: _e.mock.On("Create", ctx, req)}
}

func (_c *User_Create_Call) Run(run func(ctx context.Context, req entity.UserCreateRequest)) *User_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.UserCreateRequest))
	})
	return _c
}

func (_c *User_Create_Call) Return(_a0 model.User, _a1 error) *User_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *User_Create_Call) RunAndReturn(run func(context.Context, entity.UserCreateRequest) (model.User, error)) *User_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, userID, req
func (_m *User) Delete(ctx context.Context, userID string, req entity.UserDeleteRequest) error {
	ret := _m.Called(ctx, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, entity.UserDeleteRequest) error); ok {
		r0 = rf(ctx, userID, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// User_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type User_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - req entity.UserDeleteRequest
func (_e *User_Expecter) Delete(ctx interface{}, userID interface{}, req interface{}) *User_Delete_Call {
	return &User_Delete_Call{Call: _e.mock.On("Delete", ctx, userID, req)}
}

func (_c *User_Delete_Call) Run(run func(ctx context.Context, userID string, req entity.UserDeleteRequest)) *User_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(entity.UserDeleteRequest))
	})
	return _c
}

func (_c *User_Delete_Call) Return(_a0 error) *User_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *User_Delete_Call) RunAndReturn(run func(context.Context, string, entity.UserDeleteRequest) error) *User_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, userID, req
func (_m *User) Update(ctx context.Context, userID string, req entity.UserUpdateRequest) (model.User, error) {
	ret := _m.Called(ctx, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 model.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, entity.UserUpdateRequest) (model.User, error)); ok {
		return rf(ctx, userID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, entity.UserUpdateRequest) model.User); ok {
		r0 = rf(ctx, userID, req)
	} else {
		r0 = ret.Get(0).(model.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, entity.UserUpdateRequest) error); ok {
		r1 = rf(ctx, userID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// User_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type User_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - req entity.UserUpdateRequest
func (_e *User_Expecter) Update(ctx interface{}, userID interface{}, req interface{}) *User_Update_Call {
	return &User_Update_Call{Call: _e.mock.On("Update", ctx, userID, req)}
}

func (_c *User_Update_Call) Run(run func(ctx context.Context, userID string, req entity.UserUpdateRequest)) *User_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(entity.UserUpdateRequest))
	})
	return _c
}

func (_c *User_Update_Call) Return(_a0 model.User, _a1 error) *User_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *User_Update_Call) RunAndReturn(run func(context.Context, string, entity.UserUpdateRequest) (model.User, error)) *User_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewUser creates a new instance of User. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUser(t interface {
	mock.TestingT
	Cleanup(func())
}) *User {
	mock := &User{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
