root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  include_dir = ["internal", "cmd"]
  # include_ext = []
  # include_file = []

  cmd = "go build -o bin/netsly cmd/main.go"
  bin = "./bin/netsly"

  # Delay before trigger build after file change
  delay = 2000 # ms

  # Send Interrupt signal before killing process
  send_interrupt = true
  # Delay after sending Interrupt signal
  kill_delay = "1s" 

  log = "build-errors.log"

  # rerun = false
  # rerun_delay = 500

[log]
  time = true

# [proxy]
#   enabled = false
#   app_port = 0
#   proxy_port = 0

[screen]
  clear_on_rebuild = false
  keep_scroll = true

[misc]
  clean_on_exit = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"
