quiet: False

mockname: "{{ trimPrefix .InterfaceName `I` }}"
filename: "{{ trimPrefix .InterfaceName `I` | firstLower }}.go"

with-expecter: True
disable-version-string: True

packages:
  github.com/abc-valera/netsly-golang/internal/domain/entity:
    config:
      outpkg: "mockEntity"
      dir: "gen/mock/mockEntity"
      include-regex: ".*"
      exclude-regex: "IDependency"
