quiet: False

mockname: "{{ trimPrefix .InterfaceName `I` }}"
filename: "{{ trimPrefix .InterfaceName `I` | firstLower }}.go"

with-expecter: True
disable-version-string: True

packages:
  github.com/abc-valera/netsly-golang/internal/domain/entity:
    config:
      outpkg: "mocks"
      dir: "gen/mocks"
      include-regex: ".*"
      exclude-regex: "IDependency"
