ignoreGeneratedHeader = false
severity = "warning"
confidence = 0.8
errorCode = 0
warningCode = 0

enableAllRules = true

# Configure import blacklists for different layers
# [imports-blacklist]
#   arguments =["crypto/md5", "crypto/sha1"]

[rule.add-constant] # Maybe enable it
  Disabled = true
[rule.argument-limit]
    Disabled = true
[rule.deep-exit] # Maybe enable it
    Disabled = true
[rule.redefines-builtin-id]
    Disabled = true
[rule.function-result-limit]
    Disabled = true
[rule.blank-imports]
    Disabled = true
[rule.import-alias-naming]
    Disabled = true
[rule.cognitive-complexity]
    Disabled = true
[rule.cyclomatic]
    Disabled = true
[rule.exported]
    Disabled = true
[rule.import-shadowing]
    Disabled = true
[rule.var-naming]
    Disabled = true
[rule.package-comments]
    Disabled = true
[rule.line-length-limit]
    Disabled = true
[rule.function-length]
    Disabled = true
[rule.unhandled-error]    # Maybe enable it
    Disabled = true
    arguments = ["fmt.*"]
# [rule.unused-parameter]
#     Disabled = true
