// Code generated by mockery. DO NOT EDIT.

package query

import (
	context "context"

	model "github.com/abc-valera/netsly-api-golang/internal/domain/persistence/model"
	spec "github.com/abc-valera/netsly-api-golang/internal/domain/persistence/query/spec"
	mock "github.com/stretchr/testify/mock"
)

// MockRoom is an autogenerated mock type for the IRoom type
type MockRoom struct {
	mock.Mock
}

type MockRoom_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRoom) EXPECT() *MockRoom_Expecter {
	return &MockRoom_Expecter{mock: &_m.Mock}
}

// GetAllByUserID provides a mock function with given fields: ctx, userID, params
func (_m *MockRoom) GetAllByUserID(ctx context.Context, userID string, params spec.SelectParams) (model.Rooms, error) {
	ret := _m.Called(ctx, userID, params)

	if len(ret) == 0 {
		panic("no return value specified for GetAllByUserID")
	}

	var r0 model.Rooms
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, spec.SelectParams) (model.Rooms, error)); ok {
		return rf(ctx, userID, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, spec.SelectParams) model.Rooms); ok {
		r0 = rf(ctx, userID, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(model.Rooms)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, spec.SelectParams) error); ok {
		r1 = rf(ctx, userID, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoom_GetAllByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllByUserID'
type MockRoom_GetAllByUserID_Call struct {
	*mock.Call
}

// GetAllByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - params spec.SelectParams
func (_e *MockRoom_Expecter) GetAllByUserID(ctx interface{}, userID interface{}, params interface{}) *MockRoom_GetAllByUserID_Call {
	return &MockRoom_GetAllByUserID_Call{Call: _e.mock.On("GetAllByUserID", ctx, userID, params)}
}

func (_c *MockRoom_GetAllByUserID_Call) Run(run func(ctx context.Context, userID string, params spec.SelectParams)) *MockRoom_GetAllByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(spec.SelectParams))
	})
	return _c
}

func (_c *MockRoom_GetAllByUserID_Call) Return(_a0 model.Rooms, _a1 error) *MockRoom_GetAllByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoom_GetAllByUserID_Call) RunAndReturn(run func(context.Context, string, spec.SelectParams) (model.Rooms, error)) *MockRoom_GetAllByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockRoom) GetByID(ctx context.Context, id string) (model.Room, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 model.Room
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (model.Room, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) model.Room); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(model.Room)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoom_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockRoom_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockRoom_Expecter) GetByID(ctx interface{}, id interface{}) *MockRoom_GetByID_Call {
	return &MockRoom_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockRoom_GetByID_Call) Run(run func(ctx context.Context, id string)) *MockRoom_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRoom_GetByID_Call) Return(_a0 model.Room, _a1 error) *MockRoom_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoom_GetByID_Call) RunAndReturn(run func(context.Context, string) (model.Room, error)) *MockRoom_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByName provides a mock function with given fields: ctx, name
func (_m *MockRoom) GetByName(ctx context.Context, name string) (model.Room, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetByName")
	}

	var r0 model.Room
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (model.Room, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) model.Room); ok {
		r0 = rf(ctx, name)
	} else {
		r0 = ret.Get(0).(model.Room)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoom_GetByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByName'
type MockRoom_GetByName_Call struct {
	*mock.Call
}

// GetByName is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockRoom_Expecter) GetByName(ctx interface{}, name interface{}) *MockRoom_GetByName_Call {
	return &MockRoom_GetByName_Call{Call: _e.mock.On("GetByName", ctx, name)}
}

func (_c *MockRoom_GetByName_Call) Run(run func(ctx context.Context, name string)) *MockRoom_GetByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRoom_GetByName_Call) Return(_a0 model.Room, _a1 error) *MockRoom_GetByName_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoom_GetByName_Call) RunAndReturn(run func(context.Context, string) (model.Room, error)) *MockRoom_GetByName_Call {
	_c.Call.Return(run)
	return _c
}

// SearchAllByName provides a mock function with given fields: ctx, keyword, params
func (_m *MockRoom) SearchAllByName(ctx context.Context, keyword string, params spec.SelectParams) (model.Rooms, error) {
	ret := _m.Called(ctx, keyword, params)

	if len(ret) == 0 {
		panic("no return value specified for SearchAllByName")
	}

	var r0 model.Rooms
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, spec.SelectParams) (model.Rooms, error)); ok {
		return rf(ctx, keyword, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, spec.SelectParams) model.Rooms); ok {
		r0 = rf(ctx, keyword, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(model.Rooms)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, spec.SelectParams) error); ok {
		r1 = rf(ctx, keyword, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoom_SearchAllByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchAllByName'
type MockRoom_SearchAllByName_Call struct {
	*mock.Call
}

// SearchAllByName is a helper method to define mock.On call
//   - ctx context.Context
//   - keyword string
//   - params spec.SelectParams
func (_e *MockRoom_Expecter) SearchAllByName(ctx interface{}, keyword interface{}, params interface{}) *MockRoom_SearchAllByName_Call {
	return &MockRoom_SearchAllByName_Call{Call: _e.mock.On("SearchAllByName", ctx, keyword, params)}
}

func (_c *MockRoom_SearchAllByName_Call) Run(run func(ctx context.Context, keyword string, params spec.SelectParams)) *MockRoom_SearchAllByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(spec.SelectParams))
	})
	return _c
}

func (_c *MockRoom_SearchAllByName_Call) Return(_a0 model.Rooms, _a1 error) *MockRoom_SearchAllByName_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoom_SearchAllByName_Call) RunAndReturn(run func(context.Context, string, spec.SelectParams) (model.Rooms, error)) *MockRoom_SearchAllByName_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRoom creates a new instance of MockRoom. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRoom(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRoom {
	mock := &MockRoom{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
