// Code generated by mockery. DO NOT EDIT.

package service

import mock "github.com/stretchr/testify/mock"

// MockEmailSender is an autogenerated mock type for the IEmailSender type
type MockEmailSender struct {
	mock.Mock
}

type MockEmailSender_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEmailSender) EXPECT() *MockEmailSender_Expecter {
	return &MockEmailSender_Expecter{mock: &_m.Mock}
}

// SendEmail provides a mock function with given fields: e
func (_m *MockEmailSender) SendEmail(e Email) error {
	ret := _m.Called(e)

	if len(ret) == 0 {
		panic("no return value specified for SendEmail")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(Email) error); ok {
		r0 = rf(e)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEmailSender_SendEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendEmail'
type MockEmailSender_SendEmail_Call struct {
	*mock.Call
}

// SendEmail is a helper method to define mock.On call
//   - e Email
func (_e *MockEmailSender_Expecter) SendEmail(e interface{}) *MockEmailSender_SendEmail_Call {
	return &MockEmailSender_SendEmail_Call{Call: _e.mock.On("SendEmail", e)}
}

func (_c *MockEmailSender_SendEmail_Call) Run(run func(e Email)) *MockEmailSender_SendEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(Email))
	})
	return _c
}

func (_c *MockEmailSender_SendEmail_Call) Return(_a0 error) *MockEmailSender_SendEmail_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEmailSender_SendEmail_Call) RunAndReturn(run func(Email) error) *MockEmailSender_SendEmail_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockEmailSender creates a new instance of MockEmailSender. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEmailSender(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEmailSender {
	mock := &MockEmailSender{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
