// Code generated by mockery. DO NOT EDIT.

package service

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockTaskQueuer is an autogenerated mock type for the ITaskQueuer type
type MockTaskQueuer struct {
	mock.Mock
}

type MockTaskQueuer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTaskQueuer) EXPECT() *MockTaskQueuer_Expecter {
	return &MockTaskQueuer_Expecter{mock: &_m.Mock}
}

// SendEmailTask provides a mock function with given fields: ctx, priority, email
func (_m *MockTaskQueuer) SendEmailTask(ctx context.Context, priority TaskPriority, email Email) error {
	ret := _m.Called(ctx, priority, email)

	if len(ret) == 0 {
		panic("no return value specified for SendEmailTask")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, TaskPriority, Email) error); ok {
		r0 = rf(ctx, priority, email)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTaskQueuer_SendEmailTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendEmailTask'
type MockTaskQueuer_SendEmailTask_Call struct {
	*mock.Call
}

// SendEmailTask is a helper method to define mock.On call
//   - ctx context.Context
//   - priority TaskPriority
//   - email Email
func (_e *MockTaskQueuer_Expecter) SendEmailTask(ctx interface{}, priority interface{}, email interface{}) *MockTaskQueuer_SendEmailTask_Call {
	return &MockTaskQueuer_SendEmailTask_Call{Call: _e.mock.On("SendEmailTask", ctx, priority, email)}
}

func (_c *MockTaskQueuer_SendEmailTask_Call) Run(run func(ctx context.Context, priority TaskPriority, email Email)) *MockTaskQueuer_SendEmailTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(TaskPriority), args[2].(Email))
	})
	return _c
}

func (_c *MockTaskQueuer_SendEmailTask_Call) Return(_a0 error) *MockTaskQueuer_SendEmailTask_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTaskQueuer_SendEmailTask_Call) RunAndReturn(run func(context.Context, TaskPriority, Email) error) *MockTaskQueuer_SendEmailTask_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTaskQueuer creates a new instance of MockTaskQueuer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTaskQueuer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTaskQueuer {
	mock := &MockTaskQueuer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
