// Code generated by mockery. DO NOT EDIT.

package service

import mock "github.com/stretchr/testify/mock"

// MockUUIDMaker is an autogenerated mock type for the UUIDMaker type
type MockUUIDMaker struct {
	mock.Mock
}

type MockUUIDMaker_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUUIDMaker) EXPECT() *MockUUIDMaker_Expecter {
	return &MockUUIDMaker_Expecter{mock: &_m.Mock}
}

// NewUUID provides a mock function with given fields:
func (_m *MockUUIDMaker) NewUUID() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for NewUUID")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockUUIDMaker_NewUUID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewUUID'
type MockUUIDMaker_NewUUID_Call struct {
	*mock.Call
}

// NewUUID is a helper method to define mock.On call
func (_e *MockUUIDMaker_Expecter) NewUUID() *MockUUIDMaker_NewUUID_Call {
	return &MockUUIDMaker_NewUUID_Call{Call: _e.mock.On("NewUUID")}
}

func (_c *MockUUIDMaker_NewUUID_Call) Run(run func()) *MockUUIDMaker_NewUUID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUUIDMaker_NewUUID_Call) Return(_a0 string) *MockUUIDMaker_NewUUID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUUIDMaker_NewUUID_Call) RunAndReturn(run func() string) *MockUUIDMaker_NewUUID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUUIDMaker creates a new instance of MockUUIDMaker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUUIDMaker(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUUIDMaker {
	mock := &MockUUIDMaker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
