openapi: 3.0.0
info:
  version: 0.1.0
  title: Flugo API
  termsOfService: "https://github.com/abc-valera/flugo-api-golang"
  contact:
    email: zoocity14@gmail.com
    url: "https://github.com/abc-valera/flugo-api-golang"
  # x-logo:
  #   url: "https://apis.guru/openapi-template/logo.png"
  description: API for Flugo social network
externalDocs:
  description: Learn more about the project.
  url: "https://github.com/abc-valera/flugo-api-golang"
tags:
  - name: sign
    description: Everything about managing user sessions
  - name: me
    description: Everything about managing current user profile
  - name: users
    description: Everything about searching users
  - name: jokes
    description: Everything about searching jokes
  - name: comments
    description: Everything about searching comments
  - name: likes
    description: Everything about counting likes
servers:
  - url: "http://localhost:3000"
paths:
  /sign_up:
    $ref: paths/sign-up.yaml
  /sign_in:
    $ref: paths/sign-in.yaml
  /sign_refresh:
    $ref: paths/sign-refresh.yaml
  /me:
    $ref: paths/me.yaml
  /me/jokes:
    $ref: paths/me_jokes.yaml
  /me/comments:
    $ref: paths/me_comments.yaml
  /me/likes:
    $ref: paths/me_likes.yaml
  /comments/{joke_id}:
    $ref: paths/comments_{joke_id}.yaml
  /likes/{joke_id}:
    $ref: paths/likes_{joke_id}.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
