quiet: False

mockname: "{{ trimPrefix .InterfaceName `I` }}"
filename: "{{ trimPrefix .InterfaceName `I` | firstLower }}.go"

with-expecter: True
disable-version-string: True

packages:
  github.com/abc-valera/netsly-api-golang/internal/domain/service:
    config:
      all: True
      outpkg: "mock{{ trimPrefix .InterfaceName `I` }}"
      dir: "internal/service/{{ trimPrefix .InterfaceName `I` | firstLower }}/mock{{ trimPrefix .InterfaceName `I` }}"
  github.com/abc-valera/netsly-api-golang/internal/domain/persistence/command:
    config:
      all: True
      dir: "internal/persistence/mock/mockCommand"
      outpkg: "mockCommand"
  github.com/abc-valera/netsly-api-golang/internal/domain/persistence/query:
    config:
      all: True
      dir: "internal/persistence/mock/mockQuery"
      outpkg: "mockQuery"
  github.com/abc-valera/netsly-api-golang/internal/domain/persistence/transactioneer:
    config:
      all: True
      dir: "internal/persistence/mock/mockTransactioneer"
      outpkg: "mockTransactioneer"
