wipe = true

no-tests = true

output = "gen/sqlboiler" 
pkgname = "sqlboiler"

add-global-variants = true
add-enum-types = true

[psql]
dbname = "netsly"
host = "localhost"
port = 5432
user = "netsly"
pass = "netsly"
sslmode = "disable"